name: Comparator Client CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v1
      
      # java required for android testing
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      # flutter setup
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: install dependencies
        run: flutter pub get
      - name: perform static code analysis
        run: flutter analyze .
      - name: test
        run: flutter test
      - name: build
        run: flutter build apk
      - name: release
        uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/master'
        with:
          name: comparator-apk
          path: build/app/outputs/apk/release/comparator.apk
